<a href="https://colab.research.google.com/github/Sageh9/MSSP607/blob/main/PARTICIPATION_ACTIVITY_Week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# List of company stock files to load
files = ['aapl.csv', 'amzn.csv', 'nflx.csv', 'fb.csv', 'goog.csv']

# Dictionary to store dataframes, with company names as keys
stock_dfs = {}

# Loop through each file, read it into a dataframe, and store it
for file in files:
    company_name = file.split('.')[0]  # Extract company name from filename
    file_path = f'/content/{file}'
    try:
        df = pd.read_csv(file_path)
        stock_dfs[company_name] = df
        print(f"Successfully loaded {file} into stock_dfs['{company_name}']")
        print(f"First 5 rows of {company_name}:")
        display(df.head())
        print("\n" + "-"*50 + "\n") # Separator for readability
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
    except Exception as e:
        print(f"Error loading {file}: {e}")

Successfully loaded aapl.csv into stock_dfs['aapl']
First 5 rows of aapl:

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

--------------------------------------------------

Successfully loaded amzn.csv into stock_dfs['amzn']
First 5 rows of amzn:

         date     open     high      low    close   volume
0  2018-01-02  1172.00  1190.00  1170.51  1189.01  2694494
1  2018-01-03  1188.30  1205.49  1188.30  1204.20  3108793
2  2018-01-04  1205.00  1215.87  1204.66  1209.59  3022089
3  2018-01-05  1217.51  1229.14  1210.00  1229.14  3544743
4  2018-01-08  1236.00  1253.08  1232.03  1246.87  4279475

--------------------------------------------------

Successfully loaded nflx.csv into stock_dfs['nflx']
First 5 rows of nflx:

         date    open    high       low   close    volume
0  2018-01-02  196.10  201.65  195.4200  201.07  10966889
1  2018-01-03  202.05  206.21  201.5000  205.05   8591369
2  2018-01-04  206.20  207.05  204.0006  205.63   6029616
3  2018-01-05  207.25  210.02  205.5900  209.99   7033240
4  2018-01-08  210.02  212.50  208.4400  212.05   5580178

--------------------------------------------------

Successfully loaded fb.csv into stock_dfs['fb']
First 5 rows of fb:

         date    open    high       low   close    volume
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726

--------------------------------------------------

Successfully loaded goog.csv into stock_dfs['goog']
First 5 rows of goog:

         date     open     high      low    close   volume
0  2018-01-02  1048.34  1066.94  1045.23  1065.00  1237564
1  2018-01-03  1064.31  1086.29  1063.21  1082.48  1430170
2  2018-01-04  1088.00  1093.57  1084.00  1086.40  1004605
3  2018-01-05  1094.00  1104.25  1092.00  1102.23  1279123
4  2018-01-08  1102.23  1111.27  1101.62  1106.94  1047603

--------------------------------------------------

In [ ]:
for company_name, df in stock_dfs.items():
    df['ticker'] = company_name.upper()
    print(f"Added 'ticker' column with value '{company_name.upper()}' to {company_name} DataFrame.")
    display(df.head())
    print("\n" + "-"*50 + "\n")

Added 'ticker' column with value 'AAPL' to aapl DataFrame.

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

--------------------------------------------------

Added 'ticker' column with value 'AMZN' to amzn DataFrame.

         date     open     high      low    close   volume ticker
0  2018-01-02  1172.00  1190.00  1170.51  1189.01  2694494   AMZN
1  2018-01-03  1188.30  1205.49  1188.30  1204.20  3108793   AMZN
2  2018-01-04  1205.00  1215.87  1204.66  1209.59  3022089   AMZN
3  2018-01-05  1217.51  1229.14  1210.00  1229.14  3544743   AMZN
4  2018-01-08  1236.00  1253.08  1232.03  1246.87  4279475   AMZN

--------------------------------------------------

Added 'ticker' column with value 'NFLX' to nflx DataFrame.

         date    open    high       low   close    volume ticker
0  2018-01-02  196.10  201.65  195.4200  201.07  10966889   NFLX
1  2018-01-03  202.05  206.21  201.5000  205.05   8591369   NFLX
2  2018-01-04  206.20  207.05  204.0006  205.63   6029616   NFLX
3  2018-01-05  207.25  210.02  205.5900  209.99   7033240   NFLX
4  2018-01-08  210.02  212.50  208.4400  212.05   5580178   NFLX

--------------------------------------------------

Added 'ticker' column with value 'FB' to fb DataFrame.

         date    open    high       low   close    volume ticker
0  2018-01-02  177.68  181.58  177.5500  181.42  18151903     FB
1  2018-01-03  181.88  184.78  181.3300  184.67  16886563     FB
2  2018-01-04  184.90  186.21  184.0996  184.33  13880896     FB
3  2018-01-05  185.59  186.90  184.9300  186.85  13574535     FB
4  2018-01-08  187.20  188.90  186.3300  188.28  17994726     FB

--------------------------------------------------

Added 'ticker' column with value 'GOOG' to goog DataFrame.

         date     open     high      low    close   volume ticker
0  2018-01-02  1048.34  1066.94  1045.23  1065.00  1237564   GOOG
1  2018-01-03  1064.31  1086.29  1063.21  1082.48  1430170   GOOG
2  2018-01-04  1088.00  1093.57  1084.00  1086.40  1004605   GOOG
3  2018-01-05  1094.00  1104.25  1092.00  1102.23  1279123   GOOG
4  2018-01-08  1102.23  1111.27  1101.62  1106.94  1047603   GOOG

--------------------------------------------------

In [ ]:
# Concatenate all dataframes into a single dataframe
all_stocks_df = pd.concat(stock_dfs.values(), ignore_index=True)

print("Successfully concatenated all stock data into 'all_stocks_df'.")
print("First 5 rows of the combined DataFrame:")
display(all_stocks_df.head())

Successfully concatenated all stock data into 'all_stocks_df'.
First 5 rows of the combined DataFrame:

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [ ]:
# Save the combined DataFrame to a CSV file
output_filename = 'faanf.csv'
all_stocks_df.to_csv(output_filename, index=False)

print(f"Combined stock data saved to '{output_filename}' successfully.")

Combined stock data saved to 'faanf.csv' successfully.

In [ ]:
# Convert 'date' column to datetime
all_stocks_df['date'] = pd.to_datetime(all_stocks_df['date'])

# Convert 'volume' column to integer
all_stocks_df['volume'] = all_stocks_df['volume'].astype(int)

# Sort the DataFrame by 'date' and 'ticker'
all_stocks_df = all_stocks_df.sort_values(by=['date', 'ticker']).reset_index(drop=True)

print("Data types after conversion:")
display(all_stocks_df.info())

print("\nFirst 5 rows of the sorted DataFrame:")
display(all_stocks_df.head())

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1255 entries, 0 to 1254
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1255 non-null   datetime64[ns]
 1   open    1255 non-null   float64
 2   high    1255 non-null   float64
 3   low     1255 non-null   float64
 4   close   1255 non-null   float64
 5   volume  1255 non-null   int64
 6   ticker  1255 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 68.8+ KB

None

First 5 rows of the sorted DataFrame:

        date       open       high        low      close    volume ticker
0 2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
1 2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
2 2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
3 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
4 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX

In [ ]:
# Sort the DataFrame by 'volume' in descending order and select the top 7 rows
highest_volume_rows = all_stocks_df.sort_values(by='volume', ascending=False).head(7)

print("Seven rows with the highest volume:")
display(highest_volume_rows)

Seven rows with the highest volume:

           date      open      high       low     close     volume ticker
712  2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
267  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
287  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
272  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
910  2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
1225 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
1060 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [ ]:
# Use the melt() method to reshape the DataFrame
# 'date' and 'ticker' are kept as identifier variables (id_vars)
# The remaining columns ('open', 'high', 'low', 'close', 'volume') are melted
melted_df = pd.melt(all_stocks_df, id_vars=['date', 'ticker'],
                    var_name='metric', value_name='value')

print("First 5 rows of the melted DataFrame:")
display(melted_df.head())

print("\nLast 5 rows of the melted DataFrame:")
display(melted_df.tail())

First 5 rows of the melted DataFrame:

        date ticker metric      value
0 2018-01-02   AAPL   open   166.9271
1 2018-01-02   AMZN   open  1172.0000
2 2018-01-02     FB   open   177.6800
3 2018-01-02   GOOG   open  1048.3400
4 2018-01-02   NFLX   open   196.1000

Last 5 rows of the melted DataFrame:

           date ticker  metric       value
6270 2018-12-31   AAPL  volume  35003466.0
6271 2018-12-31   AMZN  volume   6954507.0
6272 2018-12-31     FB  volume  24625308.0
6273 2018-12-31   GOOG  volume   1493722.0
6274 2018-12-31   NFLX  volume  13508920.0